### ISSUE TITLE
No non-default port for HiSLIP possible

### ISSUE THREAD

**Issue by robsch94** [Rohde-Schwarz/RcIcPluginBugTracking#3]
As per standard, HiSLIP does not has to run on the default port 4880. When directly connecting to a device, it is possible to change the default port by appending a ',\<port\>' after hislip in the resource name as shown in the following example:
`
TCPIP0::192.168.0.100::hislip0,4881::INSTR
`
With this, a connection to the non-default port 4881 can be established.

However, the plugin does not offer a field for entering the port. And when entering the string as as custom connection, an error is show, that the resource name contains invalid characters, which is the ','. This seems to be related to the way, how the resource name is stored in the config XML.

**Comment by Miloslav-RS** [comment]
Sorry for the delay. We will not add the port entry to the standard HiSLIP connection parameters, since it is quite an exotic case. However, the custom connection will allow to entry resource names with ','. Will be fixed in version 1.4.0 coming out beginning of Jun.
In the meantime, the workaround is: Install the version 1.3.1, open the RsIcPyCharmPluginDataStorage.xml, and edit the stored resource name directly: TCPIP::10.99.2.10::hislip0__COMMA_ESC__4833

**Comment by Miloslav-RS** [comment]
We have to postpone the release because of a patent issue. If you like I can send you a beta-version

Milo

**Comment by Miloslav-RS** [comment]
Fixed in 2.0.0
